name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # -t 选项用于设置镜像的名称和标签
      - name: Build Docker image
        run: docker build -t laiyuanwen/jenkins -f ./Jenkins .

      - name: Push Docker image
        run: docker push laiyuanwen/jenkins
